-- AlterEnum IncidentType
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'CRASH';

-- AlterEnum PanicSource
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'VOICE_SOS';
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'VOICE_SILENT';
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'APPLE_CRASH';
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'ANDROID_CRASH';
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'TELEMATICS_CRASH';
ALTER TYPE "PanicSource" ADD VALUE IF NOT EXISTS 'SMART_HOME';
