-- Staff medical dispatch / crew roles (and any earlier roles added via db push)
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SALES';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TECHNICIAN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DEVELOPER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MEDICAL_DISPATCHER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MEDICAL_CREW';
