import type { AudioCueDef, HapticDef, ToneStep } from './types';

/** Short, sharp SOS identity — not a copied police/fire siren. */
const SOS_PATTERN: ToneStep[] = [
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.07 },
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.07 },
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.22 },
  { freq: 920, duration: 0.22, type: 'square', gain: 0.06, gap: 0.08 },
  { freq: 920, duration: 0.22, type: 'square', gain: 0.06, gap: 0.22 },
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.07 },
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.07 },
  { freq: 920, duration: 0.09, type: 'square', gain: 0.055, gap: 0.55 },
];

const SOS_ACK_REMINDER: ToneStep[] = [
  { freq: 720, duration: 0.07, type: 'sine', gain: 0.025, gap: 0.9 },
];

export const HAPTIC_CATALOG: Record<string, HapticDef> = {
  tap: { id: 'tap', label: 'Normal tap', pattern: [28] },
  confirmation: { id: 'confirmation', label: 'Confirmation', pattern: [35, 45, 35] },
  warning: { id: 'warning', label: 'Warning', pattern: [45, 40, 45, 80, 120] },
  critical: {
    id: 'critical',
    label: 'Critical',
    pattern: [70, 45, 70, 45, 70, 180, 70, 45, 70, 45, 70],
  },
  sos: {
    id: 'sos',
    label: 'SOS',
    pattern: [90, 60, 90, 60, 90, 200, 220, 60, 220, 200, 90, 60, 90, 60, 90],
    repeats: 2,
  },
  sos_stealth: {
    id: 'sos_stealth',
    label: 'Silent SOS (hidden)',
    pattern: [40, 90, 40, 90, 40, 280, 40, 90, 40],
  },
  success: { id: 'success', label: 'Success', pattern: [30, 40, 30] },
  connection: { id: 'connection', label: 'Connection', pattern: [28, 50, 28] },
  error: { id: 'error', label: 'Error', pattern: [40, 35, 40, 35, 40] },
  call_ring: {
    id: 'call_ring',
    label: 'Incoming call',
    pattern: [80, 100, 80, 400],
    repeats: 4,
  },
  medical: {
    id: 'medical',
    label: 'Medical',
    pattern: [90, 50, 90, 50, 90, 280],
    repeats: 2,
  },
  fire: {
    id: 'fire',
    label: 'Fire',
    pattern: [55, 35, 55, 35, 55, 35, 55],
    repeats: 3,
  },
  test: { id: 'test', label: 'Test', pattern: [25, 40, 25] },
};

export const AUDIO_CATALOG: Record<string, AudioCueDef> = {
  ui_click: {
    id: 'ui_click',
    label: 'UI click',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 1400, duration: 0.025, type: 'triangle', gain: 0.012 }],
    haptic: 'tap',
  },
  ui_toggle_on: {
    id: 'ui_toggle_on',
    label: 'Toggle ON',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 880, duration: 0.05, type: 'square', gain: 0.02 }],
    haptic: 'tap',
  },
  ui_toggle_off: {
    id: 'ui_toggle_off',
    label: 'Toggle OFF',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 520, duration: 0.05, type: 'square', gain: 0.016 }],
    haptic: 'tap',
  },
  ui_save: {
    id: 'ui_save',
    label: 'Save',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [
      { freq: 660, duration: 0.06, type: 'sine', gain: 0.025, gap: 0.04 },
      { freq: 880, duration: 0.08, type: 'sine', gain: 0.025 },
    ],
    haptic: 'confirmation',
  },
  ui_error: {
    id: 'ui_error',
    label: 'UI error',
    group: 'ui',
    loop: false,
    severity: 'warning',
    pattern: [{ freq: 180, duration: 0.18, type: 'sawtooth', gain: 0.03 }],
    haptic: 'error',
  },
  ui_navigation: {
    id: 'ui_navigation',
    label: 'Navigation',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 1000, duration: 0.02, type: 'sine', gain: 0.01 }],
    haptic: 'tap',
  },
  ui_cancel: {
    id: 'ui_cancel',
    label: 'Cancel',
    group: 'ui',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 400, duration: 0.04, type: 'triangle', gain: 0.015 }],
    haptic: 'tap',
  },
  msg_received: {
    id: 'msg_received',
    label: 'Message received',
    group: 'communication',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 880, duration: 0.07, type: 'sine', gain: 0.028, gap: 0.04 },
      { freq: 1175, duration: 0.09, type: 'sine', gain: 0.028 },
    ],
    haptic: 'tap',
  },
  call_incoming: {
    id: 'call_incoming',
    label: 'Incoming call',
    group: 'communication',
    loop: true,
    severity: 'important',
    pattern: [
      { freq: 440, duration: 0.35, type: 'sine', gain: 0.04, gap: 0.12 },
      { freq: 480, duration: 0.35, type: 'sine', gain: 0.04, gap: 0.45 },
    ],
    haptic: 'call_ring',
  },
  radio_rx: {
    id: 'radio_rx',
    label: 'Radio receive',
    group: 'communication',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 2400, duration: 0.03, type: 'square', gain: 0.012, gap: 0.02 },
      { freq: 900, duration: 0.06, type: 'sine', gain: 0.03 },
    ],
    haptic: 'tap',
  },
  radio_tx: {
    id: 'radio_tx',
    label: 'Radio transmit',
    group: 'communication',
    loop: false,
    severity: 'normal',
    pattern: [{ freq: 1100, duration: 0.07, type: 'square', gain: 0.028 }],
    haptic: 'tap',
  },
  radio_squelch: {
    id: 'radio_squelch',
    label: 'Radio squelch',
    group: 'communication',
    loop: false,
    severity: 'ui',
    pattern: [{ freq: 1800, duration: 0.04, type: 'sawtooth', gain: 0.014 }],
  },
  radio_channel: {
    id: 'radio_channel',
    label: 'Channel change',
    group: 'communication',
    loop: false,
    severity: 'ui',
    pattern: [
      { freq: 700, duration: 0.04, type: 'triangle', gain: 0.02, gap: 0.03 },
      { freq: 950, duration: 0.05, type: 'triangle', gain: 0.02 },
    ],
  },
  radio_ack: {
    id: 'radio_ack',
    label: 'Radio ACK',
    group: 'communication',
    loop: false,
    severity: 'normal',
    pattern: [{ freq: 1050, duration: 0.08, type: 'sine', gain: 0.032 }],
    haptic: 'confirmation',
  },
  connection_up: {
    id: 'connection_up',
    label: 'Connection restored',
    group: 'communication',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 520, duration: 0.08, type: 'sine', gain: 0.03, gap: 0.04 },
      { freq: 780, duration: 0.1, type: 'sine', gain: 0.03 },
    ],
    haptic: 'connection',
  },
  connection_down: {
    id: 'connection_down',
    label: 'Connection lost',
    group: 'communication',
    loop: false,
    severity: 'warning',
    pattern: [
      { freq: 480, duration: 0.12, type: 'triangle', gain: 0.03, gap: 0.05 },
      { freq: 320, duration: 0.16, type: 'triangle', gain: 0.028 },
    ],
    haptic: 'warning',
  },
  task_new: {
    id: 'task_new',
    label: 'New task',
    group: 'operations',
    loop: false,
    severity: 'important',
    pattern: [
      { freq: 740, duration: 0.1, type: 'square', gain: 0.035, gap: 0.07 },
      { freq: 990, duration: 0.14, type: 'square', gain: 0.035 },
    ],
    haptic: 'confirmation',
  },
  dispatch_new: {
    id: 'dispatch_new',
    label: 'Dispatch received',
    group: 'operations',
    loop: false,
    severity: 'important',
    pattern: [
      { freq: 2400, duration: 0.025, type: 'square', gain: 0.012, gap: 0.02 },
      { freq: 700, duration: 0.1, type: 'sine', gain: 0.035, gap: 0.06 },
      { freq: 940, duration: 0.12, type: 'sine', gain: 0.035 },
    ],
    haptic: 'confirmation',
  },
  dispatch_ack: {
    id: 'dispatch_ack',
    label: 'Dispatch accepted',
    group: 'operations',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 660, duration: 0.07, type: 'sine', gain: 0.03, gap: 0.05 },
      { freq: 880, duration: 0.09, type: 'sine', gain: 0.03 },
    ],
    haptic: 'confirmation',
  },
  en_route: {
    id: 'en_route',
    label: 'En route',
    group: 'operations',
    loop: false,
    severity: 'normal',
    pattern: [{ freq: 720, duration: 0.1, type: 'sine', gain: 0.028 }],
    haptic: 'tap',
  },
  on_scene: {
    id: 'on_scene',
    label: 'On scene',
    group: 'operations',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 620, duration: 0.08, type: 'sine', gain: 0.03, gap: 0.05 },
      { freq: 820, duration: 0.12, type: 'sine', gain: 0.03 },
    ],
    haptic: 'success',
  },
  resolved: {
    id: 'resolved',
    label: 'Incident resolved',
    group: 'operations',
    loop: false,
    severity: 'normal',
    pattern: [
      { freq: 520, duration: 0.09, type: 'sine', gain: 0.03, gap: 0.04 },
      { freq: 680, duration: 0.1, type: 'sine', gain: 0.03, gap: 0.04 },
      { freq: 860, duration: 0.14, type: 'sine', gain: 0.028 },
    ],
    haptic: 'success',
  },
  warning: {
    id: 'warning',
    label: 'Warning',
    group: 'operations',
    loop: false,
    severity: 'warning',
    pattern: [
      { freq: 640, duration: 0.14, type: 'square', gain: 0.04, gap: 0.08 },
      { freq: 480, duration: 0.18, type: 'square', gain: 0.04 },
    ],
    haptic: 'warning',
  },
  critical_warning: {
    id: 'critical_warning',
    label: 'Critical warning',
    group: 'operations',
    loop: false,
    severity: 'critical',
    pattern: [
      { freq: 700, duration: 0.1, type: 'square', gain: 0.045, gap: 0.05 },
      { freq: 700, duration: 0.1, type: 'square', gain: 0.045, gap: 0.05 },
      { freq: 700, duration: 0.22, type: 'square', gain: 0.05 },
    ],
    haptic: 'critical',
  },
  escalation: {
    id: 'escalation',
    label: 'Escalation',
    group: 'operations',
    loop: true,
    severity: 'critical',
    pattern: [
      { freq: 780, duration: 0.16, type: 'sawtooth', gain: 0.05, gap: 0.08 },
      { freq: 980, duration: 0.2, type: 'sawtooth', gain: 0.05, gap: 0.35 },
    ],
    haptic: 'critical',
  },
  device_offline: {
    id: 'device_offline',
    label: 'Device offline',
    group: 'operations',
    loop: false,
    severity: 'warning',
    pattern: [
      { freq: 300, duration: 0.18, type: 'triangle', gain: 0.035, gap: 0.1 },
      { freq: 240, duration: 0.22, type: 'triangle', gain: 0.032 },
    ],
    haptic: 'warning',
  },
  system: {
    id: 'system',
    label: 'System',
    group: 'operations',
    loop: false,
    severity: 'normal',
    pattern: [{ freq: 560, duration: 0.14, type: 'sine', gain: 0.028 }],
  },
  panic: {
    id: 'panic',
    label: 'Client SOS / Panic',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: SOS_PATTERN,
    ackReminder: SOS_ACK_REMINDER,
    haptic: 'sos',
  },
  silent_panic: {
    id: 'silent_panic',
    label: 'Silent panic',
    group: 'emergency',
    loop: false,
    severity: 'emergency',
    pattern: [],
    haptic: 'sos_stealth',
  },
  officer_sos: {
    id: 'officer_sos',
    label: 'Officer SOS',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: [
      { freq: 420, duration: 0.14, type: 'sawtooth', gain: 0.05, gap: 0.05 },
      { freq: 980, duration: 0.12, type: 'square', gain: 0.055, gap: 0.05 },
      { freq: 980, duration: 0.12, type: 'square', gain: 0.055, gap: 0.35 },
    ],
    ackReminder: SOS_ACK_REMINDER,
    haptic: 'sos',
  },
  vehicle_panic: {
    id: 'vehicle_panic',
    label: 'Vehicle panic',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: [
      { freq: 2400, duration: 0.03, type: 'square', gain: 0.014, gap: 0.02 },
      { freq: 700, duration: 0.14, type: 'sawtooth', gain: 0.05, gap: 0.06 },
      { freq: 1100, duration: 0.18, type: 'sawtooth', gain: 0.055, gap: 0.35 },
    ],
    ackReminder: SOS_ACK_REMINDER,
    haptic: 'sos',
  },
  intrusion: {
    id: 'intrusion',
    label: 'Intrusion / alarm',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: [
      { freq: 640, duration: 0.2, type: 'square', gain: 0.05, gap: 0.08 },
      { freq: 480, duration: 0.2, type: 'square', gain: 0.05, gap: 0.25 },
    ],
    haptic: 'critical',
  },
  fire: {
    id: 'fire',
    label: 'Fire emergency',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: [
      { freq: 680, duration: 0.12, type: 'triangle', gain: 0.05, gap: 0.04 },
      { freq: 520, duration: 0.12, type: 'triangle', gain: 0.05, gap: 0.08 },
    ],
    haptic: 'fire',
  },
  medical: {
    id: 'medical',
    label: 'Medical emergency',
    group: 'emergency',
    loop: true,
    severity: 'emergency',
    pattern: [
      { freq: 523, duration: 0.14, type: 'sine', gain: 0.045, gap: 0.05 },
      { freq: 659, duration: 0.14, type: 'sine', gain: 0.045, gap: 0.05 },
      { freq: 784, duration: 0.18, type: 'sine', gain: 0.045, gap: 0.45 },
    ],
    ackReminder: SOS_ACK_REMINDER,
    haptic: 'medical',
  },
  test_alert: {
    id: 'test_alert',
    label: 'Test alert (distinct)',
    group: 'emergency',
    loop: false,
    severity: 'important',
    pattern: [
      { freq: 440, duration: 0.08, type: 'sine', gain: 0.03, gap: 0.05 },
      { freq: 550, duration: 0.08, type: 'sine', gain: 0.03, gap: 0.05 },
      { freq: 660, duration: 0.08, type: 'sine', gain: 0.03, gap: 0.12 },
      { freq: 330, duration: 0.15, type: 'triangle', gain: 0.025 },
    ],
    haptic: 'test',
  },
};

export function listAudioCuesByGroup(group: AudioCueDef['group']) {
  return Object.values(AUDIO_CATALOG).filter((c) => c.group === group);
}
